from fastapi import APIRouter

from app.api.v1 import auth, buscar, caja, categorias, consultas, creditos, configuracion, cxc, ordenes, pacientes, presupuestos, productos, proveedores, reportes, sri, stats, sueldos, tesoreria, trial_lc, turnos, usuarios, ventas, whatsapp

api_router = APIRouter(prefix="/api/v1")
api_router.include_router(auth.router)
api_router.include_router(pacientes.router)
api_router.include_router(consultas.router)
api_router.include_router(categorias.router)
api_router.include_router(productos.router)
api_router.include_router(ventas.router)
api_router.include_router(tesoreria.router)
api_router.include_router(turnos.router)
api_router.include_router(ordenes.router)
api_router.include_router(reportes.router)
api_router.include_router(creditos.router)
api_router.include_router(whatsapp.router)
api_router.include_router(usuarios.router)
api_router.include_router(configuracion.router)
api_router.include_router(cxc.router)
api_router.include_router(sri.router)
api_router.include_router(buscar.router)
api_router.include_router(proveedores.router)
api_router.include_router(presupuestos.router)
api_router.include_router(stats.router)
api_router.include_router(caja.router)
api_router.include_router(trial_lc.router)
api_router.include_router(sueldos.router)
